2024-04-13T20:10:45 {"cpu": 0.93212890625, "cpu_total": 4, "cpu_usage": 0.2330322265625, "memory": 5652.0, "memory_total": 24291.0, "memory_usage": 0.23267876991478326, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039045.967098, "uuid": "9a7298ebdd304c93b5ea596e18d1f09d"}
2024-04-13T20:10:46 {"block_run_id": 302, "block_uuid": "load_coinbase_histodata", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 77, BlockRun 302: pipeline coinbase_histo block load_coinbase_histodata", "timestamp": 1713039046.371203, "uuid": "08db22770780490780fa3bb4f7a892c1"}
2024-04-13T20:10:46 {"cpu": 0.93212890625, "cpu_total": 4, "cpu_usage": 0.2330322265625, "memory": 5698.0, "memory_total": 24291.0, "memory_usage": 0.2345724754024124, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039046.512585, "uuid": "66d9947b07964abfb392500b3f3d076a"}
2024-04-13T20:10:55 {"cpu": 0.9267578125, "cpu_total": 4, "cpu_usage": 0.231689453125, "memory": 5711.0, "memory_total": 24291.0, "memory_usage": 0.23510765304022066, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039055.341594, "uuid": "5338e258095a4244b2b5bfeac047158a"}
2024-04-13T20:11:05 {"cpu": 0.9384765625, "cpu_total": 4, "cpu_usage": 0.234619140625, "memory": 5716.0, "memory_total": 24291.0, "memory_usage": 0.23531349059322382, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039065.74076, "uuid": "ba9af32978a54c7cab2b5020e355c945"}
2024-04-13T20:11:12 {"block_run_id": 302, "block_uuid": "load_coinbase_histodata", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 302 (block_uuid: load_coinbase_histodata) completes.", "timestamp": 1713039072.769672, "uuid": "c988a2fff68348fa9298bfde67d00a6f"}
2024-04-13T20:11:16 {"cpu": 0.927734375, "cpu_total": 4, "cpu_usage": 0.23193359375, "memory": 5654.0, "memory_total": 24291.0, "memory_usage": 0.2327611049359845, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039076.067004, "uuid": "688fb57e50dc489eafcbdb89632fdfb7"}
2024-04-13T20:11:16 {"block_run_id": 303, "block_uuid": "fill_na", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 77, BlockRun 303: pipeline coinbase_histo block fill_na", "timestamp": 1713039076.300727, "uuid": "84649f1e640d4680b4e95a4b6fc66a7f"}
2024-04-13T20:11:17 {"block_run_id": 303, "block_uuid": "fill_na", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 303 (block_uuid: fill_na) completes.", "timestamp": 1713039077.510362, "uuid": "ee413e90e3ee4a76bcd39c0c07581f47"}
2024-04-13T20:11:25 {"cpu": 0.92236328125, "cpu_total": 4, "cpu_usage": 0.2305908203125, "memory": 5659.0, "memory_total": 24291.0, "memory_usage": 0.2329669424889877, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039085.487772, "uuid": "846bd9ba4c174ffeb4d6d57761399258"}
2024-04-13T20:11:25 {"block_run_id": 304, "block_uuid": "tranform_histo_datatypes", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 77, BlockRun 304: pipeline coinbase_histo block tranform_histo_datatypes", "timestamp": 1713039085.71783, "uuid": "95adc0c1c40b4f75af9de2f5d140e66d"}
2024-04-13T20:11:36 {"cpu": 1.05224609375, "cpu_total": 4, "cpu_usage": 0.2630615234375, "memory": 6099.0, "memory_total": 24291.0, "memory_usage": 0.25108064715326667, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039096.009751, "uuid": "9b0eb8725dc44d37ae48d00f8f8234a1"}
2024-04-13T20:11:45 {"cpu": 1.08447265625, "cpu_total": 4, "cpu_usage": 0.2711181640625, "memory": 6552.0, "memory_total": 24291.0, "memory_usage": 0.26972952945535383, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039105.516733, "uuid": "998c4201894840ac90932eccc7caa9ea"}
2024-04-13T20:11:47 {"block_run_id": 304, "block_uuid": "tranform_histo_datatypes", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "BlockRun 304 (block_uuid: tranform_histo_datatypes) completes.", "timestamp": 1713039107.824365, "uuid": "14db8101908842849394d171e2b3bdb3"}
2024-04-13T20:11:55 {"cpu": 1.1201171875, "cpu_total": 4, "cpu_usage": 0.280029296875, "memory": 5662.0, "memory_total": 24291.0, "memory_usage": 0.2330904450207896, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039115.895319, "uuid": "cc57d0adaa144de08a70701dbdcac054"}
2024-04-13T20:11:56 {"block_run_id": 305, "block_uuid": "export_coinbase_histo", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Execute PipelineRun 77, BlockRun 305: pipeline coinbase_histo block export_coinbase_histo", "timestamp": 1713039116.121684, "uuid": "ade356e96f5449ef8edf71569ea26e91"}
2024-04-13T20:12:04 {"block_run_id": 305, "block_uuid": "export_coinbase_histo", "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "EXCEPTION", "message": "BlockRun 305 (block_uuid: export_coinbase_histo) failed.", "timestamp": 1713039124.10025, "uuid": "ec9a74aa5b824db799de74690213a2ba", "error": ["Traceback (most recent call last):\n  File \"<string>\", line 20, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 349, in export\n    __process(database=database, write_disposition=write_disposition)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 339, in __process\n    self.__write_table(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 396, in __write_table\n    return self.client.load_table_from_dataframe(df, table_id, job_config=config).result()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.BadRequest: 400 Table histo_0f34df70_4212_408e_935a_fe8a69c1c2f6_source does not have a schema.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1258, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1167, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1473, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1629, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 27, in export_data_to_big_query\nValueError: Failed to export data to BigQuery.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 750, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 92, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1654, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1163, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["Failed to export data to BigQuery."]}
Traceback (most recent call last):
  File "<string>", line 20, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 349, in export
    __process(database=database, write_disposition=write_disposition)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 339, in __process
    self.__write_table(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 396, in __write_table
    return self.client.load_table_from_dataframe(df, table_id, job_config=config).result()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Table histo_0f34df70_4212_408e_935a_fe8a69c1c2f6_source does not have a schema.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1258, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1167, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1473, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1629, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 27, in export_data_to_big_query
ValueError: Failed to export data to BigQuery.
2024-04-13T20:12:05 {"cpu": 1.13037109375, "cpu_total": 4, "cpu_usage": 0.2825927734375, "memory": 5666.0, "memory_total": 24291.0, "memory_usage": 0.23325511506319213, "pipeline_run_id": 77, "pipeline_schedule_id": 3, "pipeline_uuid": "coinbase_histo", "hostname": "dab4364d64fd", "level": "INFO", "message": "Pipeline coinbase_histo for run 77 in schedule 3 is alive.", "timestamp": 1713039125.389718, "uuid": "53e1990d8b364e1a804ac24fb5adbc16"}
